# Site settings
author: Benjamin James Stephanus
title: Let No Midlife Crisis Go Wasted
header-img: img/home-bg.png
email: ben.stephanus@gmail.com
copyright_name: Benjamin James Stephanus
description: > # this means to ignore newlines until "baseurl:"
  Why I'm interested In Web
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  noisegaze

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
